### ISSUE TITLE
Art Venture ControlNet Preprocessor Not Displaying in ComfyUI

### ISSUE THREAD

**Issue by a-ml** [sipherxyz/comfyui-art-venture#57]
After installing the Art Venture ControlNet Preprocessor via the ComfyUI Manager on a MacBook M1 Max, the preprocessor does not show any options in the dropdown, only "None" appears.

### System Information

Device: MacBook M1 Max
Operating System: macOS Sequoia 15.1
ComfyUI Version: V1  release v0.2.6
Art Venture ControlNet Preprocessor Version: 2024-10-31

### Steps to Reproduce

Installed Art Venture ControlNet Preprocessor via ComfyUI Manager.
Added the node to the workflow in ComfyUI.
Attempted to select a preprocessor, but only "None" appears in the dropdown.
Expected Behavior

The preprocessor options should appear in the dropdown.

### Actual Behavior

Only "None" is shown in the dropdown, and the preprocessor options are not accessible.

**Comment by tungnguyensipher** [comment]
This node is a wrapper of [Fannovel16's comfyui_controlnet_aux](https://github.com/Fannovel16/comfyui_controlnet_aux). If you don't have comfyui_controlnet_aux installed, or missing some dependencies and comfyui_controlnet_aux not able to load, then the node will only show "None".

Make sure you have comfyui_controlnet_aux installed correctly first. If you already install it, post the log so that I have help further.

**Comment by a-ml** [comment]
Thanks for supporting

**Comment by kondagen** [comment]
Bro you helped me like an angle....it really worked, i was scratching from 4 hours and at last you saved my day. Once again thanks BRO.
